# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(18627877-22bf-4741-88c8-a951f6fa36de)'
    subscriptionId: '18627877-22bf-4741-88c8-a951f6fa36de'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cloud-shell-storage-westeurope'
    location: 'Canada East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/MichaelCGit/VirtualMachineDeployment/main/VirtualMachine.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/MichaelCGit/VirtualMachineDeployment/main/VirtualMachine.parameters.json'
    deploymentMode: 'Complete'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
